name: KatsLegendaryWeapons
version: '${version}'
main: com.thorildsby.katslegendaryweapons.KatsLegendaryWeapons
api-version: '1.21'
commands:
  legendaries:
    description: Gives you a legendary item
    usage: /legendaries <id>
    permission: op
  ability:
    description: Activates an ability
    usage: /ability <int>
  clearCooldown:
    description: Clears all of your cooldowns
    usage: /clearCooldown
    permission: op